// export const ActionTypes = {
//     SET_PRODUCTS: "SET_PRODUCTS",
//     SELECTED_PRODUCT: "SELECTED_PRODUCT",
//     REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
//   };

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const EMPTY_CART="EMPTY_CART"
export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"


